language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsrubia
  api_key:
    secure: IMK3Pn9lb2OKHTQ8h4FJzb4UDphtnJfGF6z8ZjfUa4rHNgNV/g95+/1+laQadMluTr0/qgjf0NwsgBTcz2l+FNA3LS+mOUp3JA+6xyJCT/LY5heh8A8dXmoXhuuYVphl3C2VTF4mjiEztktRY9t1gLVZhZEvkLIuPjjLGbtwi0jDa/sD9jjIMp+4uP3qbDU991R4ZyL2sSj/LEIey7q1FQqBmOmcJ3zVbpwwS6//wRXBZW5sKhKv0364LjJSabUoQjFQCTZuZhgDzlKJT1Chr5/sA1cmssC6b8k9fNbtDeyoPZ0dhSoTKt12+mIq/xLIYd7RT1WADRpe6xgWUB9qt9ZaOLIhnhbV8pdtxxpF1jhIOxZd7YWFs0OkGcEJg6DpiMLhaA6O2Ii32T+lIrOYIpWadRhn4ylLrXPp4kWI+4u1wBZlNEJQGtShTQOQXF++shQVHh65RGIlflwyLoK5Af+s+25qvDaRaSiBNEKYJVZjXEzaDee8bS3Njh+FJaQdIFm9BWFIdkgFQb8xfmhYFIrJol2Auv45VWIewFwySesIJnvcNOLnAUdO50bFAcZ3mfrtaovZTKwyWYungDj8tM66456H2bX3J5r6fH63XpjxuEKYMgVgaU6zON94u1zG5vUP+SR+C43H7Vzi692WbacmKZMlqQzsz5Ti655B5/Y=
